### ISSUE TITLE
Create builds for Windows

### ISSUE THREAD

**Issue by techtonik** [Igalia/piglit#1]
It would be much convenient to create builds that end users can run. This will help to create white/black lists for certain features and make game engines such as https://github.com/godotengine/godot/issues/1162 more stable with certain hardware.

**Comment by techtonik** [comment]
While disabling certain feature, game engine may refer to specific number in piglit bugs database, and users would be able to rerun the test to confirm the issue (for example that the issue is not fixed with latest drivers).

**Comment by samuelig** [comment]
Hello Techtonik,

This is not the official repository for piglit. This is a clone of the official repo where Igalia is working on before submitting patches upstream.

If you want to contact the piglit community to discuss this issue you can either send an email to the mailing list <piglit@lists.freedesktop.org> or submit a bug report in its bugzilla: https://bugs.freedesktop.org/

Thanks for your understanding,

Sam

**Comment by techtonik** [comment]
This list https://lists.freedesktop.org/archives/piglit/2016-February/thread.html looks like it is not for humans. Anyway, can Igalia provide Windows binaries?

**Comment by techtonik** [comment]
Added https://bugs.freedesktop.org/show_bug.cgi?id=94045 for upstream.

**Comment by samuelig** [comment]
Right now Igalia doesn't have any plan to provide Windows binaries for piglit. Our work is currently focused on GNU/Linux machines.

Thanks for submitting the bug upstream.
