### ISSUE TITLE
32-on-64 bit build instructions doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [Igalia/piglit#2]
README says:

> if cross-compiling a 32-bit build on a 64-bit host, then you must
invoke cmake with option "-DCMAKE_SYSTEM_PROCESSOR=i386".

But,

	$ make clean
	$ cmake -DCMAKE_SYSTEM_PROCESSOR=i386 .             
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/constantine/Projects/piglit
	$ make
	[  0%] Generating tests/util/piglit-dispatch-gen.c, tests/util/piglit-dispatch-gen.h, tests/util/piglit-util-gl-enum-gen.c
	[  0%] Built target piglit_dispatch_gen
	[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-log.c.o
	[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-util.c.o
	[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-util-egl.c.o
	^C
	[interrupt output skipped]
	$ file target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-log.c.o
	target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-log.c.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped

cmake version: 3.7.2
make version: GNU Make 4.2.1

**Comment by samuelig** [comment]
This looks like a problem in either your development environment or piglit itself. As this is not the official piglit repository, please open a bug in Bugzilla explaining the issue:

https://bugs.freedesktop.org/enter_bug.cgi?product=piglit

or send an email to the mailing list: https://lists.freedesktop.org/mailman/listinfo/piglit
