### ISSUE TITLE
problem in retrievable_hint.c

### ISSUE THREAD

**Issue by overpair** [Igalia/piglit#3]
in tests/spec/arb_get_program_binary/retrievable_hint.c, line 82:

	got_error = piglit_check_gl_error(0);

should it be?

	got_error = !piglit_check_gl_error(0);

**Comment by jasuarez** [comment]
Thanks for the catch up! Yes, it seems the check is wrong.

I'll submit a patch on your behalf to fix it.

**Comment by jasuarez** [comment]
This patch has been accepted and pushed in Piglit upstream.

https://cgit.freedesktop.org/piglit/commit/?id=fc34afe442df6bb6a32fc49294b0ce7428a0e9e3
