### ISSUE TITLE
how to use  --test-list  ?

### ISSUE THREAD

**Issue by xxxxxsssss** [Igalia/piglit#4]
I  tried :
$ ./piglit run     --test-list=./bin/gl-3.0-forward-compatible-bit       results
and:
$./piglit run  --test-list  ~/cmd_bin.txt   results/
it not work.
can anyone tell me how to ues " ./piglit  run  --test-list" ?

**Comment by samuelig** [comment]
Please send the question to the mailing list piglit@lists.freedesktop.org. This is an unofficial repository where igalians push their code before submitting it to the official one :-)
